# Use official Python 3.11 image
FROM python:3.11-slim

# Set working directory inside container
WORKDIR /usr/seedor

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy the rest of the app code
COPY . .

ENV ENV=dev 

# Expose port for FastAPI (default 8000)
EXPOSE 8000

# Command to run FastAPI using uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
